#!/usr/bin/env python3
"""
scripts/generate_seed_from_nav.py
-----------------------------------
Reads nav_floor_data.json and generates the rooms + nodes block
for seed.ts — so you don't have to hand-type 29 room records.

Run:
    python3 scripts/generate_seed_from_nav.py \
        --input  src/data/nav_floor_data.json \
        --output scripts/seed_rooms_generated.ts
"""

import json
import argparse
import math
from pathlib import Path

ROOM_TYPE_MAP = {
    "BOARDROOM":          "BOARDROOM",
    "CONFERENCE":         "MEETING_ROOM",
    "MEETING":            "MEETING_ROOM",
    "PAX":                "MEETING_ROOM",
    "TRAINING":           "MEETING_ROOM",
    "VISITOR":            "MEETING_ROOM",
    "BREAKOUT":           "MEETING_ROOM",
    "THINKING":           "MEETING_ROOM",
    "TEAM_COLLAB":        "MEETING_ROOM",
    "RECEPTION":          "RECEPTION",
    "CABIN":              "OFFICE",
    "DIRECTOR":           "OFFICE",
    "EXECUTIVE":          "OFFICE",
    "CFO":                "OFFICE",
    "MD_CABIN":           "OFFICE",
    "PD_HD":              "OFFICE",
    "ODC":                "OPEN_WORKSPACE",
    "OPEN":               "OPEN_WORKSPACE",
    "CAFETERIA":          "PANTRY",
    "PANTRY":             "PANTRY",
    "DRY_PANTRY":         "PANTRY",
    "KITCHEN":            "PANTRY",
    "TOILET":             "TOILET",
    "REST_ROOM":          "TOILET",
    "SHOWER":             "TOILET",
    "HAND_WASH":          "TOILET",
    "WASH":               "TOILET",
    "STORE":              "STORAGE",
    "STORAGE":            "STORAGE",
    "HUB_ROOM":           "SERVER_ROOM",
    "BATTERY":            "SERVER_ROOM",
    "NOVAC":              "SERVER_ROOM",
    "IT_STORE":           "STORAGE",
    "GYM":                "OTHER",
    "RECREATION":         "OTHER",
    "SICK":               "OTHER",
    "COMPACTOR":          "OTHER",
    "POT_WASH":           "OTHER",
    "REPRO":              "OTHER",
    "PHONE":              "OTHER",
    "ATTENDANCE":         "OTHER",
    "PUNCHING":           "OTHER",
}

def infer_type(code: str) -> str:
    code_upper = code.upper()
    for keyword, room_type in ROOM_TYPE_MAP.items():
        if keyword in code_upper:
            return room_type
    return "OTHER"

def infer_capacity(name: str, width_mm, height_mm) -> str:
    name_l = name.lower()
    # Extract from name if present (e.g. "8 PAX MEETING")
    import re
    m = re.search(r'(\d+)\s*pax', name_l)
    if m:
        return str(int(m.group(1)))
    if width_mm and height_mm:
        area_m2 = (width_mm / 1000) * (height_mm / 1000)
        if "cafeteria" in name_l:
            return str(int(area_m2 * 1.5))
        if "meeting" in name_l or "conference" in name_l or "board" in name_l:
            return str(max(4, int(area_m2 / 2)))
        if "odc" in name_l or "workspace" in name_l:
            return str(int(area_m2 / 4))
    return "null"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default="src/data/nav_floor_data.json")
    parser.add_argument("--output", default="scripts/seed_rooms_generated.ts")
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    rooms = data["rooms"]
    floor_id = data["floorId"]
    scale_x = data["scaleX"]
    scale_y = data["scaleY"]

    lines = [
        "// AUTO-GENERATED by generate_seed_from_nav.py",
        "// Paste this into scripts/seed.ts replacing the gfRooms array",
        "// and gfNodes array.",
        "",
        f"// Floor: {data['buildingName']} — Level {data['level']}",
        f"// Grid: {data['gridCols']}×{data['gridRows']}  scale: {scale_x}m/cell × {scale_y}m/cell",
        f"// Real size: {data['realWidthM']}m × {data['realHeightM']}m",
        "",
        "const gfRooms = [",
    ]

    for r in rooms:
        rtype = infer_type(r["code"])
        cap   = infer_capacity(r["name"], r["widthMm"], r["heightMm"])
        lines += [
            "  {",
            f'    id:        "{r["id"]}",',
            f'    code:      "{r["code"]}",',
            f'    name:      "{r["name"]}",',
            f'    type:      RoomType.{rtype},',
            f'    capacity:  {cap},',
            f'    gridX:     {r["gridX"]},',
            f'    gridY:     {r["gridY"]},',
            f'    gridW:     {r["gridW"]},',
            f'    gridH:     {r["gridH"]},',
            f'    centreX:   {r["centreX"]},',
            f'    centreY:   {r["centreY"]},',
            f'    qrCode:    "{r["qrCode"]}",',
            "  },",
        ]

    lines += ["];", ""]

    # Generate entry nodes — one per room, at the room's grid position
    lines += ["const gfNodes = ["]
    for r in rooms:
        lines += [
            "  {",
            f'    id:     "node-gf-{r["id"].replace("room-gf-","")}-entry",',
            f'    roomId: "{r["id"]}",',
            f'    gridX:  {r["gridX"]},',
            f'    gridY:  {r["gridY"]},',
            f'    realX:  {r["centreX"]},',
            f'    realY:  {r["centreY"]},',
            f'    type:   NodeType.ROOM_ENTRY,',
            f'    label:  "{r["name"]}",',
            "  },",
        ]
    lines += ["];", ""]

    lines += [
        "// ── NEXT STEP ────────────────────────────────────────────────────────────────",
        "// After pasting into seed.ts, add corridor junction nodes manually.",
        "// Look at the grid visual to find corridor intersections (T-junctions, crossings).",
        "// Add them as NodeType.CORRIDOR_JUNCTION entries in gfNodes.",
        "// Then connect everything in gfEdges.",
        "//",
        "// Grid scale reference:",
        f"//   1 grid cell X = {scale_x}m",
        f"//   1 grid cell Y = {scale_y}m",
        f"//   Total floor:   {data['realWidthM']}m × {data['realHeightM']}m",
    ]

    out = "\n".join(lines)
    # Replace any non-ASCII characters that Windows cp1252 can't handle
    out = out.replace("\u2014", "--").replace("\u2013", "-").replace("\u2019", "'")
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(out, encoding="utf-8")
    print(f"✓ Written {args.output}")
    print(f"  {len(rooms)} rooms and {len(rooms)} entry nodes generated")
    print(f"  Next: add corridor junction nodes manually, then define edges")

if __name__ == "__main__":
    main()
